autotest/autotest-docker

- subtests/docker_cli/dockerhelp/dockerhelp.py
> dockerhelp: Add todo for docker 1.4.1

- control
> control: Ignore individually inaccessable bugs

- control
> control: Fix TypeError on BZ include

- .dockerignore
- Dockerfile
- config_defaults/subtests/docker_cli/attach.ini
- config_defaults/subtests/docker_cli/build.ini
- config_defaults/subtests/docker_cli/create.ini
- config_defaults/subtests/docker_cli/dockerinspect.ini
- config_defaults/subtests/docker_cli/negativeusage.ini
- config_defaults/subtests/docker_cli/run.ini
- config_defaults/subtests/docker_cli/run_exec.ini
- config_defaults/subtests/docker_cli/run_volumes_selinux.ini
- config_defaults/subtests/docker_cli/start.ini
- config_defaults/subtests/docker_cli/stop.ini
- config_defaults/subtests/docker_cli/top.ini
- config_defaults/subtests/docker_cli/wait.ini
- config_defaults/subtests/docker_daemon/network.ini
- subtests/docker_cli/build/build.py
- subtests/docker_cli/dockerimport/truncated.py
- subtests/docker_cli/logs_follow/logs_follow.py
- subtests/docker_cli/negativeusage/negativeusage.py
- subtests/docker_cli/save_load/save_load.py
- subtests/docker_cli/stop/stop.py
- subtests/docker_cli/workdir/workdir.py
Lots of config & test changes for new ``--tty`` behaviour change in docker-1.4  Also a collection of various other fixes found along the way.
> Test maintenance for recent docer versions

- .dockerignore
- Dockerfile
- config_defaults/subtests/docker_cli/attach.ini
- config_defaults/subtests/docker_cli/build.ini
- config_defaults/subtests/docker_cli/create.ini
- config_defaults/subtests/docker_cli/dockerinspect.ini
- config_defaults/subtests/docker_cli/negativeusage.ini
- config_defaults/subtests/docker_cli/run.ini
- config_defaults/subtests/docker_cli/run_exec.ini
- config_defaults/subtests/docker_cli/run_volumes_selinux.ini
- config_defaults/subtests/docker_cli/start.ini
- config_defaults/subtests/docker_cli/stop.ini
- config_defaults/subtests/docker_cli/top.ini
- config_defaults/subtests/docker_cli/wait.ini
- config_defaults/subtests/docker_daemon/network.ini
- subtests/docker_cli/build/build.py
- subtests/docker_cli/logs_follow/logs_follow.py
- subtests/docker_cli/negativeusage/negativeusage.py
- subtests/docker_cli/save_load/save_load.py
- subtests/docker_cli/stop/stop.py
- subtests/docker_cli/workdir/workdir.py
Rebase/Squash autosquash commit messages
> Non tty cfg

- config_defaults/subtests/docker_cli/build.ini
- subtests/docker_cli/build/build.py
> Two quick fixes

- index.rst
> Doc ext dep

- config_defaults/subtests/docker_cli/run_attach.ini
- dockertest/dockercmd.py
- dockertest/dockercmd_unittests.py
- run_pylint.sh
- subtests/docker_cli/logs_follow/logs_follow.py
- subtests/docker_cli/rm/rm.py
- subtests/docker_cli/run_attach/run_attach.py
> Deprecate execute calls

- subtests/docker_cli/run_env/run_env.py
Check if container removal list exists in cleanup().  Improve
output checking to use dockertest API.  Added additional debugging.
> run_env: Improve reliability & messaging

- .gitignore
- Makefile
- conf.py
- dockertest/documentation.py
- dockertest/textwriter.py
- index.rst
- run_checkdocs.py
- subtests/docker_cli/run_ipc_mem/run_ipc_mem.py
- subtests/docker_cli/run_sigproxy/run_sigproxy.py
- subtests/docker_cli/save_load/save_load.py
- subtests/docker_cli/stop/stop.py
- subtests/docker_cli/top/top.py
> Docs: Update docs for additional test trees

- config_defaults/subtests/docker_cli/run_volumes_selinux.ini
- subtests/docker_cli/run_volumes_selinux/run_volumes_selinux.py
Test wasn't exercizing positive and negative modes in a consistent
manner, and failing.  Fixed negative case to match opposite of positive.
> run_volumes_selinux: Fix test consistency

- config_defaults/subtests/docker_cli/top.ini
- dockertest/output.py
- dockertest/output_unittests.py
- subtests/docker_cli/top/runsleep.py
- subtests/docker_cli/top/top.py
Original test was hopelessly broken
> Docker top

- atomic_install.sh
> Atomic: Fix config.ini production bug

- config_defaults/defaults.ini
- config_defaults/subtests/docker_cli/create.ini
- config_defaults/subtests/docker_cli/pull.ini
- config_defaults/subtests/docker_cli/run.ini
- config_defaults/subtests/docker_cli/tag.ini
> Fix example centos tags centos7 -> 7

- subtests/docker_cli/attach/attach.py
In this case, it will execute docker run command with a 5s timeout and no pre-check
whether the image exist.The patch will introduce two functions to check and pull the image
if it does not exist.
*Add pre-check of whether image exist before run
*Add pull image function if the image is not exist
Signed-off-by: Time Su <lsu@redhat.com>
> Fix attach case issue

- config_defaults/subtests/docker_cli/commit.ini
- subtests/docker_cli/commit/check_default_cmd.py
Resolve #497
*Change the container's execute command to fit current docker
*Update the check point
> Fix commit check_default_cmd sub test

- subtests/docker_cli/cp/cp.py
Resolve #502 
*simple subcase: change file directory to /
*every_last: add postprocess function
> Fix cp case

- subtests/docker_cli/run_volumes/run_volumes.py
- subtests/docker_cli/run_volumes/volumes_one_source.py
Resolve #510
*Change base class cleanup function to staticmethod
*Rewrite volumes_on_source volume option 'Z' to 'z'
> docker_cli/run_volume fix volumes_one_source unused path_info

- config_defaults/subtests/docker_cli/run_volumes.ini
- config_defaults/subtests/docker_cli/syslog.ini
- dockertest/subtest.py
- subtests/docker_cli/run_volumes/file_volume.py
- subtests/docker_cli/run_volumes/run_volumes.py
- subtests/docker_cli/syslog/syslog.py
Fixes up Syslog test, adds error condition for non-existing sub-subtests requested, adds file_volumes (disabled) sub-subtest.
> Syslog journal

- subtests/docker_cli/run_volumes/run_volumes.py
A minor fix
*Initialize path_info, cmdresults before use them
> docker_cli/run_volumes make up initialize for few vairbles

- conf.py
> Docs: Enabled intersphynx extension

- .travis.yml
- index.rst
> docs: Add lables to a few section headers

- index.rst
> Docs: Add label for configuration section

- index.rst
> docs: Add label for additional test trees

- config_defaults/subtests/docker_cli/dockerimport.ini
- subtests/docker_cli/dockerimport/truncated.py
> dockerimport/truncate: Use offset instead of percentage

- subtests/docker_cli/info/info.py
> Prevent test failure on non-loop setups

- config_defaults/defaults.ini
> Bump minimum acceptable autotest version

- subtests/docker_cli/start/start.py
> Fix start test to use proper image

- config_defaults/defaults.ini
Signed-off-by: Afom Michael <tmichael@redhat.com>
> Removed unnecessary token

- config_defaults/subtests/docker_cli/invalid.ini
> Update docker_cli/invalid/image new error msg

- subtests/docker_cli/dockerinspect/dockerinspect.py
- subtests/docker_cli/dockerinspect/inspect_all.py
- subtests/docker_cli/dockerinspect/inspect_keys.py
> dockerinspect: Always log inspect output

- subtests/docker_cli/create/create.py
- subtests/docker_cli/create/create_signal.py
> Create-signal: Negative-Test incorrectly testing for 0 exit

- dockertest/output.py
- dockertest/output_unittests.py
Preserves old behavior and supports new table format
> version: Fix parsing > 1.7.1 version table

- .travis.yml
> Travis: Bump pylint version slightly as workaround

- subtests/docker_cli/build/build.py
> Base class build command debugging on exception

- config_defaults/subtests/docker_cli/create.ini
- run_pylint.sh
- subtests/docker_cli/create/create_signal.py
- subtests/docker_cli/kill/kill_utils.py
- subtests/docker_cli/kill_stopped/kill_utils.py
- subtests/docker_cli/kill_stress/kill_utils.py
- subtests/docker_cli/top/top.py
> Fix create signal and create remote tag

- .travis.yml
- dockertest/config_unittests.py
- dockertest/containers_unittests.py
- dockertest/dockercmd.py
- dockertest/documentation.py
- dockertest/documentation_unittests.py
- dockertest/images_unittests.py
- dockertest/networking.py
- dockertest/output.py
- dockertest/output_unittests.py
- run_checkdocs.py
- subtests/docker_cli/build/build.py
- subtests/docker_cli/negativeusage/negativeusage.py
A few changes that occurred to me while browsing for the Travis CI results.
> Update travis ci

- subtests/docker_cli/dockerinspect/inspect_keys.py
> Label keys are not subjects for style inspection

- subtests/docker_cli/iptable/iptable.py
Previously complex girations were used to determine
networking devices.  Recent docker versions rely on
IP addresses in iptables instead, so switch to using those.
> Fix/Tweak iptables test to use IPAddress

- subtests/docker_cli/info/info.py
Also adds checks for new items.
> Fix info test false-fail multi-pool

- index.rst
Minor spelling, grammar, and consistency cleanup.
> (Minor) Language corrections in docs

- subtests/docker_cli/info/info.py
> Fix test as per BZ 1304808

- config_defaults/subtests/docker_cli/run_env.ini
- subtests/docker_cli/run_env/run_env.py
Simple for now but w/ room for future expansion
> Fantasticly simplify/hone run_env subtest

- intratests/garbage_check/garbage_check.py
- run_pylint.sh
- run_unittests.sh
- subtests/docker_cli/info/test_info.py
> Fix garbage_check AttributeError + bunch of other stuff

- config_defaults/subtests/docker_cli/run_volumes.ini
- subtests/docker_cli/run_volumes/run_volumes.py
> run_volumes: Add ability to execute optional pre-testing command

- dockertest/subtestbase.py
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
> typo correction, NBD :)

- control
> Arg parsing bug

- index.rst
The quickstart formerly recommended resetting back to the tag
of the current version.  However, this means any between-version
fixes are skipped.  Esp. between 0.8.4 and HEAD, in combination with
changes in docker's output will cause the version test to fail.
Because the latest master HEAD is more likely to be bug-free, it's a
much better starting-off point for anyone following the quickstart.
Also updated the prerequisites section to include the 'Atomic' platforms
as well as make the runtime vs devel. software dependencies more distinct.
Docker Autotest is more than happy to run as-is on Atomic, but extra
bits are helpful for documentation and/or development work.
> Update quickstart documentation and Prerequisites

- .travis.yml
- config_defaults/subtests/docker_cli/load.ini
- config_defaults/subtests/docker_cli/negativeusage.ini
- dockertest/dockercmd_unittests.py
- dockertest/images.py
- dockertest/images_unittests.py
- dockertest/output.py
- dockertest/output_unittests.py
- run_pylint.sh
- run_unittests.sh
- subtests/docker_cli/build/build.py
- subtests/docker_cli/events/events.py
- subtests/docker_cli/events/test_event_parsing.py
- subtests/docker_cli/import_url/import_url.py
- subtests/docker_cli/load/load.py
- subtests/docker_cli/negativeusage/negativeusage.py
- subtests/docker_cli/run_attach/run_attach.py
- subtests/docker_cli/run_cgroup_parent/run_cgroup_parent.py
- subtests/docker_cli/run_cidfile/run_cidfile.py
- subtests/docker_cli/tag/tag.py
This is pretty huge. It's impossible to review in one chunk, that's why I've taken great pains to git-rebase into manageable chunks. I'm not sure how github handles this as a PR, though. If you can review individual commits, I suggest doing so. If you can't, let me know and I'll work on submitting smaller individual PRs.
> Docker 1.10

- subtests/docker_cli/run_attach/run_attach.py
- subtests/docker_cli/run_user/run_user.py
> minor typo fixes

- conf.py
- config_defaults/defaults.ini
- dockertest/version.py
> Dockertest Version 0.8.5 (NO API Changes)

- config_defaults/subtests/docker_cli/login.ini
- dockertest/subtestbase.py
- subtests/docker_cli/login/login.py
Various forms of docker login/logout, including push with/without valid credentials.
> Test docker login

- config_defaults/subtests/docker_cli/run.ini
- subtests/docker_cli/run/run_tmpfs.py
Signed-off-by: Afom Michael <tmichael@redhat.com>
> Adding run test with tmpfs option

- dockertest/containers.py
- dockertest/output/dockertime.py
- dockertest/subtestbase.py
- subtests/docker_cli/dockerinspect/dockerinspect.py
- Documented one exception in new failif_not_in()
- Fixed minor spelling/syntax errors in other doc strings
> (minor): sphinx comment fixes

- config_defaults/control.ini
- config_defaults/defaults.ini
- intratests/garbage_check/garbage_check.py
> Tidy-up ini linewraps + remove dupe entry

- intratests/garbage_check/garbage_check.py
> Pylint fixes for garbage_check

- config_defaults/subtests/docker_cli/kill_stress.ini
> sigh, missed one

- subtests/docker_cli/run_cgroups/memory.py
I lost much of a day due to missing error messages from
this test. Let's avoid having that happen again.
> Cleanup: better diagnostics from run_cgroups/memory

- subtests/docker_cli/stop/stop.py
Fix a disaster waiting to happen: a check function with a
180-degree-misleading error message, almost certainly caused
by copy-pasting another function. I haven't seen it trigger,
but it if ever did, I pity the person debugging it.
Found accidentally while investigating a test failure in
nearby code. Cleaned up the whole thing, reducing duplication.
> stop test: cleanup

- config_defaults/control.ini
- config_defaults/defaults.ini
- dockertest/subtestbase.py
- dockertest/subtestbase_unittests.py
- subtests/redhat/packaging/packaging.py
- subtests/redhat/rhel_push_plugin/rhel_push_plugin.py
N/B: There's an un-squashed **fixup!** here
> Fix a few failing jobs in docker autotest CI / ADEPT

- intratests/garbage_check/garbage_check.py
Once or twice or many times a month, a run fails with
repeated failures in each garbage_check step: "found
leftover <none>". I've just been ignoring those, manually
deleting the <none> images, and restarting tests.
Apparently garbage_check was supposed to deal with
those in a more dignified manner. This PR fixes the
bugs that were preventing it from doing so.
> Clean up leftover <none> images

- config_defaults/subtests/docker_cli/start.ini
A better description for dkrcmd_waittime parameter
> Signed-off-by: Afom Michael <tmichael@redhat.com>

- subtests/docker_cli/build/build.py
> Fix build test spelling logwarn -> logwarning

- dockertest/environment.py
> Oops. Missed one instance in arg name change

- config_defaults/subtests/docker_cli/run_volumes_selinux.ini
- control
- dockertest/dockercmd.py
- dockertest/output/validate.py
- pretests/log_sysconfig/log_sysconfig.py
- subtests/docker_cli/run_volumes_selinux/run_volumes_selinux.py
The main change here is the commit ``run_volumes_selinux: Seperate + Improve start detection``.  The rest are mostly fluff.  For whatever reason, I wasn't able to install pylint to check any of this, so I'm relying on CI to do that.
> Improve run volumes selinux

- config_defaults/control.ini
- control
> Add docker-latest to list of BZ components to scan

- config_defaults/subtests/docker_cli/build.ini
- dockertest/images.py
- dockertest/subtest.py
- dockertest/subtestbase.py
- subtests/docker_cli/build/addurl.py
- subtests/docker_cli/build/build.py
- subtests/docker_cli/build/cache.py
- subtests/docker_cli/build/expose.py
- subtests/docker_cli/build/onbuild.py
> Fix build stuff

- index.rst
The quickstart was very old, and not representitive of modern output.
Also cleanup docs pertaining to selecting/including/excluding tests.
Make the ``--args`` command-line option usage, and the ``control.ini``
usage more clear.
> Docs: Update quickstart and test-selection section

- .papr.yml
Rename file to new name and update link to docs.
> ci: rename to new name

- conf.py
- config_defaults/defaults.ini
- dockertest/version.py
> Dockertest Version 0.8.8 (NO API Changes)

- subtests/docker_cli/run_cgroups/memory.py
> Refactor: remove horrible duplication in cgroups

- config_custom/control.ini
> Greatly reduce subtest set to basic workflow

- config_defaults/subtests/docker_cli/cp.ini
- subtests/docker_cli/cp/cp.py
...especially into a path pointed to by a symlink.
Confirms two CVEs, plus regressions introduced in
the fixing thereof
> New subtest: cp_symlink, tests copying into container
