autotest/autotest-docker

config_defaults/subtests/docker_cli/run_volumes.ini
dockertest/docdeps.py
dockertest/documentation_unittests.py
index.rst

Some config. option descriptions are quite complex,
but previous parsing always stripped out all extra
whitespace.  Introduce new-style string formatting
map to allow substituting special characters in
final description parsing stages.  Update unittests
accordingly.

documentation: Allow nesting newlines and tabs

---

config_defaults/subtests/docker_cli/kill.ini
config_defaults/subtests/docker_cli/kill_stopped.ini
config_defaults/subtests/docker_cli/kill_stress.ini
subtests/docker_cli/kill/kill.py
subtests/docker_cli/kill/kill_utils.py
subtests/docker_cli/kill_parallel_stress/kill_utils.py
subtests/docker_cli/kill_stopped/kill_stopped.py
subtests/docker_cli/kill_stopped/kill_utils.py
subtests/docker_cli/kill_stress/kill_stress.py
subtests/docker_cli/kill_stress/kill_utils.py

Resolves: #422 
Removed all non-tty enabled sub-subtests as they are now invalid.  Also
added signal 18 to the skip list since it cannot be reliably tested.

kill_stress: Fix improper tests

---

config_defaults/defaults.ini
config_defaults/subtests/docker_cli/run_env.ini
subtests/docker_cli/run_env/run_env.py

Test was using --tty incorrectly (no pty attached).  Test
was also incorrectly checking stdout vs stderr in some situations.
Test had hard-coded docker daemon options that didn't match current
release options.  Added 'daemon_options' global to defaults, updated
test to use it.

run_env: Fix several bugs

---

config_defaults/subtests/docker_cli/wait.ini
index.rst
subtests/docker_cli/wait/wait.py

Fixes https://github.com/autotest/autotest-docker/issues/120
This patch modifies the config to by default use names only in
one subtests. All other subtests use ids. This way we have
deterministic behavior while still testing booth ways.
Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>

subtests.docker_cli.wait: Make it deterministic

---

config_defaults/subtests/docker_cli/logs.ini
subtests/docker_cli/logs/basic.py
subtests/docker_cli/logs/logs.py

The LC_ALL method still fails in my machine, then i have a idea that
use utc instead of config the LC_ALL env.
*Use utc as timestamp thus we can ignore the effect of LC_*

docker_cli/logs use utc instead of LC_ALL

---

config_defaults/control.ini
control

Instead of manually listing subtest names associated to one or more
bugzillas, search for them based on query values and status
at the same time.

Control: Automatically find bugzillas associated to docker-autotest

---

config_defaults/subtests/docker_cli/run_exec.ini

`docker exec --interactive` will trigger utils.run's timeout, so that remove
it from default configuration file.

docker_cli/run_exec: remove exec --interactive option from config

---

config_defaults/subtests/docker_cli/diff.ini

*The `touch /usr` will not be effect if `/usr` has already existed.
Use `chmod 777 /home` to replace

docker_cli/diff: change diff_change default option

---

control

This catches the top-level 'Fault' exception from the bugzilla module.
When thrown, it prints a warning w/ exception info then continues as if
no tests were blocked.

control: Don't abort testing on bugzilla exception

---

control

Convert timeout from float to int, no string. Otherwise tests fails with:
10:31:25 ERROR| Traceback (most recent call last):
10:31:25 ERROR|   File "/usr/lib64/python2.7/logging/__init__.py", line 859, in emit
10:31:25 ERROR|     msg = self.format(record)
10:31:25 ERROR|   File "/usr/lib64/python2.7/logging/__init__.py", line 732, in format
10:31:25 ERROR|     return fmt.format(record)
10:31:25 ERROR|   File "/usr/lib64/python2.7/logging/__init__.py", line 471, in format
10:31:25 ERROR|     record.message = record.getMessage()
10:31:25 ERROR|   File "/usr/lib64/python2.7/logging/__init__.py", line 335, in getMessage
10:31:25 ERROR|     msg = msg % self.args
10:31:25 ERROR| TypeError: %d format: a number is required, not str

Convert timeout from float to int, no string. Otherwise tests fails.

---

dockertest/config.py
dockertest/config_unittests.py
dockertest/subtest.py

A check for undefined sub-subtests was incorrectly matching
unrelated parent subtests based on one subtest's name being
a prefix to another.
Signed-off-by: Chris Evich <you@forgot.to.edit.gitconfig>

Fix exclusion filter matching prefixed names

---

control
dockertest/config.py
dockertest/subtest.py

* Follow directory symlinks when searching subtests and configs
* Fix SubSubtestCaller.initialize()

Symlink support

---

control

This fixes an issue with the stateless design of the control file.  Though it significantly clutters up the debug log, it is now properly recording state so a crash or reboot during testing should be supported to resume.

Control unroll

---

config_defaults/subtests/docker_cli/run_cgroups.ini
subtests/docker_cli/run_cgroups/cpushares.py

* Test was looking under wrong JSON key for configured value
* Maximum value for cpu shares is now limited
* Negative testing now supports docker commands that fail

Fix run_cgroups test for cpu and memory

---

config_defaults/defaults.ini

This option is intended for environments where a specific
version MUST be locked in, perhaps due to upstream API/behavior
changes.  Normally however, Docker Autotest should just run with
whatever the latest/greatest autotest version is installed.

Don't check Autotest version by default

---

config_defaults/subtests/docker_cli/dockerimport.ini

GNU tar 1.27 [*] allows --preserve-order (aka --same-order)
only with archive reading commands; the import test was
using it with --create, causing test to fail on f22 & f23.
[*] commit 74ce228

import subtest: remove --preserve-order tar option

---

dockertest/images.py
dockertest/images_unittests.py
intratests/garbage_check/garbage_check.py

* Additional regex magic & processing is needed when a FQIN is specified
without the repo-address component.
* Images module now uses key-words to reference components of FQIN
group matches
* Added new unittests to verify above changes
* Updated garbage_check to be more flexible when comparing against
configured images to preserve.

Fix garbage_check not preserving image IDs

---

.travis.yml
run_unittests.sh
subtests/docker_cli/info/info.py
subtests/docker_cli/info/test_info.py

verify_pool_name() checks that the Docker Pool Name listed
by 'docker info' is present in the output of 'dmsetup ls'.
We cannot rely on the output order of the latter: on one
RHEL7 system it outputs the desired pool name first, on
another system last. So let's just test for the presence
of the desired pool name anywhere in the output.
Also, create a unit test for the new code. Invocation is
ugly but that should be fixable by someone more python-
proficient than I. Fixes welcome.
Unit test requires python-nose and python-unittest2, both
of which are available on RHEL7.

info subtest: fix verify_pool_name()

---

subtests/docker_cli/rmi/rmi.py

rmi with_blocking_container_by_tag test was failing:
repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"
Root cause: DockerImage.get_unique_name("FOO") generates a name
of the form "<testname>_FOO_<rand>". If FOO is ":tag" (colon-tag),
as it was in this test, we get "<testname>_:tag_<rand>" and
docker doesn't like the trailing underscore in "<testname>_".
Fix: use "suffix:tag" instead of ":tag" for unique_name prefix.
Also: removed confusing test descriptions, making it clearer (I
hope) what this subtest does.
Also: fixed what I believe was use of incorrect variable name
in error message.

fix rmi subtest failure

---

config_defaults/subtests/docker_cli/tag.ini
subtests/docker_cli/tag/tag.py

subtest tag:double_tag was failing. Root cause: too many
to list. I don't think this test could have ever completed
successfully.
Fixes:
+ Principally, reworked the way we check exit status
when we're expecting the command to fail (i.e.
two 'docker tag' commands in a row without -f).
Related fixes:
+ moved some logic from the config file to the code:
1) docker_expected_result (PASS/FAIL): this absolutely
does not belong in a config file. There is no
circumstance under which an end user would want
to say "oh hey let's expect double-tag to pass"
or "let's expect other-test to fail". This is
code logic, not configuration logic.
2) -f flag (in double_tag_force): again, this is
code logic. It's the whole defining factor of
the test itself. It is harmful to imply that
an end user should be able …

Fix test failure in double_tag subsubtest.

---

config_defaults/defaults.ini

Commit 7f7decaef8c7f76041d56 removed `ATOMIC_SUBSTITUTIONS` value from `config_defaults/defaults.ini`, but it left comma at the end of previous line, so when it is split by commas, it returns one "empty string" value and tests fail.

fix dangling comma in `defaults.ini`

---

config_defaults/control.ini
control

Matching bugs containing multiple subthing names should now be possible.

Update control.ini comments + BZ searching

---

control

The Monkeypatch is used on sys.path to include the test directory in
module search path.  This is needed to support adding the
python-bugzilla module to the test-directory on systems where installing
elsewhere is impossible/impractical (i.e. Atomic).  The no-execute
argument is primarily intended for debugging control.ini and bugzilla
search options.

Monkeypatch and add no-execute control argument

---

control
dockertest/subtest.py

This gets around a special case where a subtest has only a single sub-subtest which is excluded (control file cannot inspect sub-subtests, only identify their names).

Monkey fix and avoid empy subtest throwing error

---

config_defaults/subtests/docker_cli/kill_bad.ini

Found while testing docker 1.9.1-el7: 'kill -s 48' in the kill_bad
subtest now succeeds because 48 is a valid, if unusual, signal.
Looks like change was introduced in August 2015 via
0e50d946a25beb134bce2aaf4a209b5cfcbacf8f
Submitting as a lone PR because this is 1.9-related but technically
not part of the new exit code work.

signal 48 (SIGRTMIN+14) is now valid

---

dockertest/output.py
dockertest/subtest.py
subtests/docker_cli/create/create_signal.py
subtests/docker_cli/rmi/rmi.py

Raises DockerTestNAError if currently-installed docker
version is less than a specified requirement.
Also: removed obsolete version checks and code from rmi

Refactor: new subtest.require_docker_version()

---

config_defaults/defaults.ini

Though in CI, generally daemon_options is overridden, having it here by
default is more useful than having it on the client.  The later is
infrequently useful and at worse problematic for output parsers.  Easier
to just drop it.

Re-locate -D to it's more useful place

---

config_defaults/subtests/docker_cli/run_cgroup_parent.ini
subtests/docker_cli/run_cgroup_parent/run_cgroup_parent.py

Test that --cgroup-parent=X and X-Y behave as expected.
Test valid only on docker >= 1.9.1-25.el7 and >= 1.10.

bz1320302 - docker --cgroup-parent=X

---

config_defaults/subtests/docker_cli/commit.ini
config_defaults/subtests/docker_cli/history.ini
config_defaults/subtests/docker_cli/pull.ini
config_defaults/subtests/docker_cli/rmi.ini
dockertest/dockercmd_unittests.py
dockertest/output.py
dockertest/output_unittests.py
subtests/docker_cli/attach/attach.py
subtests/docker_cli/build/build.py
subtests/docker_cli/commit/commit.py
subtests/docker_cli/create/create_signal.py
subtests/docker_cli/dockerimport/truncated.py
subtests/docker_cli/history/history.py
subtests/docker_cli/import_url/import_url.py
subtests/docker_cli/kill_bad/kill_bad.py
subtests/docker_cli/pull/pull.py
subtests/docker_cli/rm/rm.py
subtests/docker_cli/rmi/delete_wrong_name.py
subtests/docker_cli/rmi/rmi.py
subtests/docker_cli/run_cidfile/run_cidfile.py
subtests/docker_cli/run_dns/run_dns.py
subtests/docker_cli/run_exec/run_exec.py
subtests/docker_cli/start/simple.py

Background: 'docker run' exit codes will be changing in 1.10,
to differentiate between container exit status and errors from
docker itself[1]. This commit prepares for that, by
redefining the use of the docker_expected_status config
setting. Instead of 'PASS' or 'FAIL' (old values), it
is now expected to be an integer: 0 for success, X
for failure. As of this commit X is always 1, but at
some future point that will change. When it does,
the new failif_ne() helper will display the new exit
code, and it will be easy to update .ini files as
necessary.
Additionally, the mustfail() helper now requires the
expected exit status as an argument. These statuses can
actually be hardcoded in the code itself, because
mustfail() tests (once) if the installed docker binary
returns unique exit codes; if …

bz1097344 (docker-1.10 exit codes): prep work

---

subtests/docker_cli/dockerinspect/inspect_keys.py

Seems like a simple mistype: code was attempting to
reference the wrong dict, leading to test failure.

dockerinspect/inspect_keys : trivial bug fix

---

dockertest/output.py
subtests/docker_cli/run_dns/run_dns.py

docker <1.10 does *not* exit 1 on all errors: on daemon errors,
it exits 2. Recognize that in mustfail() by converting 125
(new 1.10 exit code for daemon errors) to 2.
Also: fix one test case. "bad search" was used as an argument
to the --dns-search option. This would work if we ran docker
via exec, or quoting args, but when run via shell it becomes:
docker ... --dns-search bad search --privileged ...
...which unsurprisingly results in the following error:
Unable to find image 'search:latest' locally
Trying to pull repository [...]/search ... not found
...which of course has exit code 1, not 2. (TL;DR this test case
was not actually testing what it intended to).

exit codes: fix docker-daemon corner case

---

subtests/docker_cli/rmi/rmi.py

The rmi test is leaving stale images behind, causing
garbage_check to fail on it and all subsequent tests.
This harmless cleanup code deletes images even if
their name has been clobbered by bz1317096.

Workaround for bz1317096 : clean up stale images

---

subtests/docker_cli/kill_bad/kill_bad.py
subtests/docker_cli/start/simple.py

Two instances -- kill and start -- which really seem like docker
daemon exit codes (i.e. docker <1.10 should exit 2) are exiting 1.
Don't understand it and am giving up on trying. We'll have to sort
this out when docker-1.10 comes out.

Yet more exit code cleanup

---

subtests/docker_cli/commit/commit.py

Running docker with --detach, just to get a CID, exposes us to
a race condition if we check the container contents before the
command has completed.
Solution: use --name=<rand name> instead. That seems to be the
standard convention on other tests.
Also: clean up a diagnostic message: failif_ne() now displays
the expected and actual values, so caller doesn't have to

commit subtest: fix race condition

---

index.rst
run_unittests.sh
subtests/docker_cli/dockerinspect/test_inspect_keys.py
subtests/docker_cli/events/test_event_parsing.py
subtests/docker_cli/info/test_info.py

Looks like it's being abandoned. Oh well; it was nice
while it lasted.

Remove dependency on python-nose

---

run_pylint.sh

Apropos of nothing, sort file list before running tests. It
just helps greatly with readability and especially when
looking for results on a recently-touched file.

run_pylint: predictable execution order

---

subtests/docker_cli/attach/attach.py
subtests/docker_cli/build/build.py
subtests/docker_cli/cp/cp.py
subtests/docker_cli/create/create_remote_tag.py
subtests/docker_cli/images_all/images_all.py
subtests/docker_cli/iptable/iptable.py
subtests/docker_cli/kill/kill_utils.py
subtests/docker_cli/kill_bad/kill_bad.py
subtests/docker_cli/kill_stopped/kill_utils.py
subtests/docker_cli/kill_stress/kill_stress.py
subtests/docker_cli/kill_stress/kill_utils.py
subtests/docker_cli/logs/logs.py
subtests/docker_cli/negativeusage/negativeusage.py
subtests/docker_cli/ps_size/ps_size.py
subtests/docker_cli/pull/pull.py
subtests/docker_cli/rm/rm.py
subtests/docker_cli/run/run.py
subtests/docker_cli/run_attach/run_attach.py
subtests/docker_cli/run_cidfile/run_cidfile.py
subtests/docker_cli/run_dns/run_dns.py
subtests/docker_cli/run_env/run_env.py
subtests/docker_cli/run_user/run_user.py
subtests/docker_cli/save_load/save_load.py
subtests/docker_cli/tag/tag.py
subtests/docker_cli/wait/wait.py

When looking at a debug log of a failure, the first and
most important thing I want to know is: what docker commands
led to this? Too often it's not in the log, and I see this
in the source:
DockerCmd(...., verbose=False)
...requiring an edit, and rerunning the test, then (when not
trivially reproducible) rerunning and rerunning some more.
Enough. Let's just always log docker commands. Since verbose
is the default, just remove most instances of verbose=False.
(And, while we're at it, also remove verbose=True since
it's a possibly-misleading NOP).
Also: fixed minor misspellings.

DockerCmd : always run with verbose

---

config_defaults/subtests/docker_cli/run_cgroup_parent.ini
subtests/docker_cli/run_cgroup_parent/run_cgroup_parent.py

The error message for --cgroup-parent=/xxxxx (invalid name)
changed between docker-1.9 and 1.10

docker run --cgroup-parent: error message change

---

subtests/docker_cli/import_url/import_url.py

The import_url test runs a docker command that's expected to fail:
docker run Not-A-Valid_Image some dummy command
docker-1.9 consistently fails with "some" not in $PATH
docker-1.10 fails in three (AFAICT) different ways:
exec: "some": executable file not found in $PATH
Then one of these three errors:
docker: Error response from daemon: Cannot start container <cid>: [9] System error: invalid character 'e' looking for beginning of value.
docker: Error response from daemon: Cannot start container <cid>: [9] System error: json: cannot unmarshal string into Go value of type libcontainer.generic Error.
docker: Error response from daemon: Container command not found or does not exist..
...and an exit code of 125 (first two) or 127 (last). This makes it
impossible to test with mustfail(). …

import_url: inconsistent exit codes in docker-1.10

---

subtests/docker_cli/run_user/run_user.py

docker changed two error messages, just minor capitalization
changes that were enough to trip up our tests[1].
Since the change has now propagated into docker-1.9.1-37.el7
and docker-latest-1.10.3-22.el7, I choose to just change
the hardcoded tested-for error message. No configurability,
no regexes or flexibility, just holding my nose and accepting
that this is sometimes part of life in testland.
[1] https://github.com/docker/docker/commit/da38ac6c79fe902ed0687afc73d731c95c6d491a#diff-29081af54e3d2dea9c82ab2e757e61bf

run_user test: change capitalization of docker msg

---

run_pylint.sh
run_unittests.sh

It's been an unwritten rule that the pyhong 'print'
statement shouldn't appear anywhere in module or test code.
Additionally, while used for debugging, the pdb module also
shouldn't appear in any checked-in code.  Update run_pylint
to with a function to check for both of these.
There is no easy way to add these checks to pylint/pep8.  In
the case of pylint and pdb, the workaround is to mark the pdb
module itself as deprecated instead.  This ensures all the possible
ways of importing it are checked.
In the case of print, the simplest solution is to just egrep
for it in every checked file.  If found, the file and line
references are printed.
Finally, I added a check for AUTOTEST_PATH or successful autotest
import, similar to the one that appears in run_unittests.sh
Signed-off-by: Chris …

Extra run_pylint checking

---

config_defaults/subtests/docker_cli/create.ini
config_defaults/subtests/docker_cli/negativeusage.ini
subtests/docker_cli/create/create.py
subtests/docker_cli/negativeusage/negativeusage.py
subtests/docker_cli/run/run.py

Added parameters to run negativeusage test with wrong parameters to --tmpfs
Signed-off-by: Afom Michael <tmichael@redhat.com>

Adding negativeusage parameters to --tmpfs

---

config_defaults/subtests/docker_cli/create.ini
subtests/docker_cli/create/create_tmpfs.py

Adding a create container subtest with --tmpfs option and inspecting the
created container for the --tmpfs parameter
Signed-off-by: Afom Michael <tmichael@redhat.com>

Adding create subtest with --tmpfs option

---

subtests/docker_cli/login/login.py

Not all subsubtests create a login auth file. In cleanup,
check before removing a nonexistent file.

(minor) login test: cleanup: fix exception

---

dockertest/config.py
dockertest/config_unittests.py
intratests/garbage_check/garbage_check.py
subtests/docker_cli/run_volumes/run_volumes.py

https://github.com/autotest/autotest-docker/issues/572
The omit_empty=False default caused another problem in
ADEPT tests this week. I can think of no sensible reason
for passing back empty values in the usual case.

github issue #572: default omit_empty=True in get_as_list()

---

dockertest/subtest.py

When summarizing subtest results, treat DockerTestNAError
as a passing subsubtest.
FIXME: this could potentially mask real problems, such as
run_volumes skipping because of a wrong config setting or
one of the expecting-docker-1.10 tests skipping even though
the test system should have 1.10. I don't have any good ideas
on how to address this.

Treat DockerTestNAError as PASS

---

dockertest/subtestbase.py
dockertest/subtestbase_unittests.py
run_unittests.sh

failif_not_in(needle, haystack) now allows needle to be
a pipe-separated list of possibilities. The idea is to
allow support for multiple docker versions:
foo.ini:
expected_stderr = this is what docker-1.10 says
| docker-1.12 says something completely different
Since it's getting complicated, add new unit tests.
Also: run_unittests wrapper: bug fix: we were ignoring error
exit status from the first test to exit.

failif_not_in() : allow multiple needles

---

subtests/docker_cli/run_sigproxy/run_sigproxy.py

...at least, it's acting like a race condition (unpredictable
failures), even though on examination it looks like a pretty
clear bug that should fail every time.
The problem seems to be that some containers are run with --detach,
hence we don't see READY in stdout. Solution: use 'docker logs' in
addition to checking stdout. But why do the tests pass sometimes??

run_sigproxy test: race condition fix

---

config_defaults/subtests/redhat/packaging.ini
subtests/redhat/packaging/packaging.py

bz1280068 - make sure docker binary ships with debuginfo

New meta-test: confirm debug symbols

---

config_defaults/subtests/redhat/rhel_push_plugin.ini
subtests/redhat/README
subtests/redhat/rhel_push_plugin/rhel_push_plugin.py

rhel_push_plugin tries to prevent docker push of a RHEL-based
image, where "RHEL-based" seems to be defined (via hardcoding
in the plugin) as:
for each layer:
run docker inspect
True if Vendor is "Red Hat, Inc." and
Name starts with "rhel"
otherwise False
Test by building images with variations of the above, and
making sure docker push is blocked (with the expected message)
when RHEL-based and allowed otherwise.

rhel_push_plugin test

---

config_defaults/subtests/docker_cli/start.ini
subtests/docker_cli/start/simple.py

'docker logs -f' doesn't seem to be real-time: in simple
manual tests, I've seen it take 15 seconds for the STARTED
message to appear in the docker logs output. This is, I
believe, what causes the start/simple test to fail seemingly
at random on some runs. FWIW 'docker logs' (without the -f)
has no such lag. I don't know if this is a stdout buffering
issue or if -f is implemented by sleep-check (vs select).
Workaround: call `docker logs` directly, in a loop, waiting for
two STARTEDs.
Also: removed unused code and config settings, cleaned up
some confusing comments.

start/simple subtest: extend 'docker logs' timeout

---

dockertest/dockercmd.py
subtests/docker_cli/run_sigproxy/run_sigproxy.py

Other subtests (e.g. kill and possibly run_cidfile) are
experiencing spurious failures that look suspiciously like
the race condition that prompted wait_for_ready() in
run_sigproxy, i.e. we may be starting tests on containers
that aren't fully running yet.
This moves wait_for_ready() into a method of AsyncDockerCmd.
It's kind of complicated because we need to determine our
own container's ID, and that's not trivial or robust, but
for our purposes I think it's safe enough.
There is no corresponding method for DockerCmd, because it
only makes sense if invoked with --detach, and even in that
case there's no sane way to get the container ID.
In order to keep things simple, this is purely a refactor
with no extra functionality. If this code is acceptable, I'll
follow up with PRs for other …

refactor: make wait_for_ready() reusable

---

config_defaults/subtests/docker_cli/kill.ini
config_defaults/subtests/docker_cli/kill_stress.ini
config_defaults/subtests/docker_cli/negativeusage.ini
config_defaults/subtests/docker_cli/run_cgroup_parent.ini
subtests/docker_cli/login/login.py
subtests/docker_cli/tag/tag.py
subtests/docker_cli/top/runsleep.py

- kill, kill_stress: docker now silently ignores SIGPIPE
(see docker commit 55a367d), so passthrough (--sig-proxy)
no longer works. Add it to the skip list.
- negativeusage:
- ip1: remove --force option from tag. Option no longer
exists in docker 1.12, and it isn't necessary in 1.10
- error message changes.
- run_cgroup_parent: allow any prefix before error (docker,
docker-current, /usr/bin/docker-current, etc)
- login: error message changes. "no successful auth challenge"
is gone. "401 Unauthorized" remains, and that's good enough.
- login: add a FIXME noting that the --email option to login
is now deprecated
- tag: -f (force) option removed in 1.12
- top: better diagnostics

get tests working under docker 1.12

---

config_defaults/subtests/docker_cli/kill.ini
config_defaults/subtests/docker_cli/kill_stopped.ini
subtests/docker_cli/kill/kill_utils.py
subtests/docker_cli/kill_stopped/kill_utils.py
subtests/docker_cli/kill_stress/kill_utils.py
subtests/docker_cli/run_cidfile/run_cidfile.py

- kill subtest: use new wait_for_ready()
- run_cidfile subtest: allow time for container to
appear in 'docker ps' output. Also, document a
rare and hard-to-fix SIGPIPE.

More fixes for race conditions

---

config_defaults/subtests/docker_cli/namespaces.ini
subtests/docker_cli/namespaces/namespaces.py

In particular, a way to detect that either docker is run
with MountFlags=latest in systemd unit file, or the kernel
issue requiring that flag is fixed (not expected until 7.3+).

New test for mount namespaces

---

config_defaults/control.ini

Needed to support skipping of certain tests based
on results of bugzilla query.  The search is limited
to specific components, not all current/relevant
were listed.

Add runc component for optional bugzilla integration

---

control
dockertest/containers.py
dockertest/images.py
pretests/docker_test_images/docker_test_images.py

It's easier for subtests to timeout if they're required to pull the test
image across a network of unknown capacity.  However, no test here is
exercizing network bandwidth, so any pull-related timeouts are failures
to be avoided.
The default control file does not impose the global timeout onto
pretests.  Add a pre-test that pulls the default testing image, and
optionally additional images.  Also optionally (default: False) update
the config_custom/defaults.ini file (if it exists) with these images.
Finally, log information about all images that exist on the system into
the sysinfo results directory.  This makes it easy to find the initial
repository state of the system, including image ID's.

Pre-pull test images to save subsubtest timeout

---

config_defaults/subtests/docker_cli/diff.ini

In case the /usr/bin directory is blocked from removal (due to mounts
most likely), just remove a file instead.

Fix diff test for blocked dir removal

---

config_defaults/subtests/docker_cli/stop.ini
subtests/docker_cli/stop/stop.py

Another few hours lost to a transient failure. On two of my
virts, for reasons I don't understand, docker image spinup
is taking many seconds. More than the 'sleep 3' previously
hardcoded in the stop test. Solution: switch to wait_for_ready()
instead of hardcoded sleep. And, since I'm seeing lots of
these sort of timeouts, make it 10 seconds.

Race condition fix: stop test

---

config_defaults/subtests/docker_cli/kill.ini
config_defaults/subtests/docker_cli/kill_stopped.ini
config_defaults/subtests/docker_cli/kill_stress.ini
config_defaults/subtests/docker_cli/run_sigproxy.ini

From 3-5s to 10s. Most of the time these subtests pass just fine,
but once in a while they fail while waiting for READY. This could
just be system load, I don't know what causes it. But extending
the timeout doesn't hurt, because wait_for_ready() triggers as
soon as the container issues READY -- it's not a sleep, we're
not wasting those 10 seconds. And with this extension we should
see fewer false alarms, which means less wasted developer time.

Bump up some wait_for_ready timeouts

---

config_defaults/intratests.ini
dockertest/docker_daemon.py
dockertest/docker_daemon_unittests.py
intratests/garbage_check/garbage_check.py

...including possibly editing run options. Tricky bits:
- determining docker vs docker-latest
- preserving a backup of original system options
- making sure we restore that when done
- making double-sure, in gc, that we leave no trace

Functionality for restarting docker daemon

---

config_defaults/subtests/docker_cli/run.ini
subtests/docker_cli/run/run_install.py

With some base images (those lacking iputils), the run_ping test must
perform two operations.  Both are required for the sub-subtest to
pass, which can make it difficult to identify higher-level repo. /
install problems vs ping-related problems.
This commit adds a new sub-subtest, and a new option ``install_cmd``.  When
non-empty, this command will be logically ANDed along with ``cmd``.
A simplistic check for ``bash -c`` was added since ``&&`` is
shell-specific.
The new ``run_install`` test uses the ``install_cmd`` twice.  Once to
verify that installation works, including with existing packages.
The run_ping test was updated to use this option instead of jamming both
commands together on it's own.  Though the eventual docker command is
unchanged, it makes the configuration cleaner and …

Replace run_ping with run_install

---

control
dockertest/subtest.py

All sub-subtests defined in a subtest's ``subsubtests`` config.
option must have corresponding config. sections.  However, if a
sub-subtest is excluded by an open bugzilla, the code assumes
it's configuration section must exist.  This is not always the
case, esp. if the excluded sub-subtest was removed from config.
Introduce a new property that grants access to only the exclusions
returned by bugzilla (if any).  During initialization of either
"caller" subtest, refrain from including these bugzilla excluded
items in the subsubtest_names attribute.

Fix bzexclude

---

config_defaults/subtests/docker_cli/negativeusage.ini

PR 608 added three tests for invalid use of --tmpfs. All three
turned out to be fragile: docker-1.12 fails in a different
manner than 1.10. After an hour's effort I'm unable to come up
with any equivalent tests that fail similarly in 1.10 & 1.12,
so it seems best to just remove them entirely. There is still
an actual test for --tmpfs functionality.

Remove failing --tmpfs tests

---

control

It's not possible to have a variable timeout across steps, they all need
to be defined up-front before anything runs.  This meant quick tests
disproportionately utilize their time vs long tests.  Instead, remove
the individual timeouts and fudge-factor.  Autotest will then impose the
global (``TIMEOUT``) value.  This could cause a cascade failure of all
subsequent tests, if one consumes too much time.  This could make
results hard to debug in the worst-case, but the best-case (no timeouts)
should make the run-to-run results more consistent.

Remove individual subtest timeouts

---

config_defaults/subtests/docker_cli/systemd.ini
subtests/docker_cli/systemd/Dockerfile
subtests/docker_cli/systemd/docker-build.service
subtests/docker_cli/systemd/docker-pull.service
subtests/docker_cli/systemd/p4321.service
subtests/docker_cli/systemd/systemd.py
subtests/docker_cli/systemd/systemd_run.py

Remove some duplication; remove unnecessary intermediate steps
(i.e. use same variable names in .ini file and in source files;
don't edit files in-place, just transform as we copy); expand
brvtd variable names into legible ones; remove trailing whitespace;
add a missing super()

Pr653 cleanup

---

config_defaults/subtests/docker_cli/start.ini
subtests/docker_cli/start/start.py

To address recent failures, I added a dkrcmd_waittime for dkrcmd.wait of start subtest to have enough time for long_term_app and rerun_long_term_app 'sleep 100' command to finish instead of bailing after 60 sec.

Adding a waittime parameter to start subsubtest

---

dockertest/docker_daemon.py
pretests/log_versions/log_versions.py
subtests/docker_cli/version/version.py

Write a new sysinfo/docker_rpm file containing
the output of 'rpm -q docker[*]' (* - docker or
docker-latest). This requires exporting which_docker()
from dockertest.docker_daemon.
Purpose: post-run analysis can look at failures,
then cross-reference against a TBD table of known
subtest failures in specific docker builds.

Log docker rpm version

---

dockertest/subtest.py
subtests/docker_cli/negativeusage/negativeusage.py

- add missing log_step() on cleanup
- fix misleading comment (copy-paste error)
- negativeusage: handle rare exception when initialize()
fails early

fix minor bugs encountered during ignore-known-failures work:

---

.gitignore
config_defaults/defaults.ini
config_defaults/subtests/docker_cli/negativeusage.ini
config_defaults/subtests/docker_cli/run.ini
run_unittests.sh
subtests/docker_cli/build/build.py

Fixes several test failures on the latest/greatest RHEL w/ docker-1.12.5.
The 'display failing output check in build test' commit depends on #672 being merged first.

Addendum to #672

---

.travis.yml
dockertest/environment.py
subtests/docker_cli/run_volumes_selinux/run_volumes_selinux.py

This test will fail if the --scontext option happens to not exist.
In any case, options to the 'ls' command could be different across
distros / versions or change unpredictably (WRT docker autotest).
Instead, add an API call to retrieve the context directly from the
extended attribute value.  This works on all filesystems and whether or
not SELinux is enabled.

Fix run_volumes_selinux depending on ls command

---

pretests/log_versions/log_versions.py

A given system may have docker but not docker-latest (or,
rarely, vice-versa). Such situations lead to CmdError
failure in the log_versions pretest.
Solution: allow errors in 'rpm -q' command. If 'is not installed'
appears in command output, return empty string which will in turn
be written to the docker_rpm_xxx file.
Alternate solutions considered: returning the 'is not installed'
string itself, or dealing with it in write_sysinfo() by not
writing the docker_rpm_xxx file. IMO both of those make it
harder for client code.

log_versions: handle missing rpms

---

.travis.yml
dockertest/environment.py
index.rst

Also update documentation indicating hat libselinux-python or pyxattr
are required dependencies.  However, SELinux is not native under Ubuntu
(which travis CI runs) so some extra work will be needed to 100% convert
to using the preferred libselinux-python.  Added a TODO to this effect.

Fix missing pyxattr module in Fedora Atomic

---

subtests/docker_cli/syslog/syslog.py

i.e. bump up seek from -4k to -8k. Also, improve the
diagnostics:
- test failed
- Did not find expected message 'foo' in last N lines of syslog
...so if/when we see this again the poor test engineer has
some chance of understanding what happened and then investigating.

syslog test: try reading more syslog lines

---

dockertest/dockercmd.py
dockertest/dockercmd_unittests.py
subtests/docker_cli/pull/pull.py

there's an inf. loop in ``while not dockercmd.done``

Fix pull timeout

---

control

super-duper quick-and-dirty so we can get info. ASAP from CI.

Add intratest to log recent AVC audit messages

---

config_defaults/subtests/docker_cli/negativeusage.ini

I realize this test failure is subject of some debate.  However that's orthagonal to getting some useful runtime out of it, while we wait (maybe indefinitely) for a bug fix.   The original reproducer and a comment about the BZ is preserved in the configuration.

Workaround RH BZ 1393572 & docker_cli/negativeusage/iv4

---

subtests/docker_cli/selinux_labels/selinux_labels.py
subtests/docker_cli/selinux_labels/test.sh

The script was setting the return-code variable but never actually
exiting with it.  Add exit statement at the end to fix that.

Fix selinux_labels bash script to exit with a code

---

control

Support for BZ searching for excluded tests is completely optional.  If
for any reason it fails (like a bad SSL Cert Validate), ignore the failure.

Fix: Control exit on any BZ-related exception

---

subtests/docker_cli/login/login.py

If one of the early steps in initialize() fails, cleanup()
barfs with KeyError. Avoid that.

login test cleanup: deal with early failure

---

subtests/docker_cli/login/login.py

in docker logout:
- Remove login credentials for
+ Removing login credentials for
Deal with both.

docker 1.13 changes a word in an error message

---

config_defaults/subtests/redhat/rhel_push_plugin.ini

from ErrorCodeUnauthorized to ErrorCodeDenied. Accept
either error message.

docker-1.13 changes error code for rhel-push-plugin

---

Dockerfile
config_defaults/defaults.ini
config_defaults/pretests.ini
config_defaults/subtests/docker_cli/build.ini
config_defaults/subtests/docker_cli/create.ini
config_defaults/subtests/docker_cli/run.ini
config_defaults/subtests/docker_cli/tag.ini
index.rst
subtests/docker_cli/build/addurl/Dockerfile
subtests/docker_cli/build/bad/Dockerfile
subtests/docker_cli/build/dockerignore/Dockerfile
subtests/docker_cli/build/expose/Dockerfile
subtests/docker_cli/build/full/Dockerfile
subtests/docker_cli/build/jsonvol/Dockerfile
subtests/docker_cli/build/part/Dockerfile

Some places, the CentOS image is still referenced because for those
specific tests, it's better to use a non-default image.  Also, in most
places, updated the CentOS tag from 7 -> latest.  Mainly for cosmetic
purposes, though it does squah any confusion that perhaps the 7-GA
version was being used.
Note: CI testing will most likely not be useful on this PR since it's setup for CentOS only (currently).

Switch default testing to RHEL from CentOS

---

subtests/docker_cli/syslog/syslog.py

If syslog.initialize() bails out with TestNAError (because
of missing syslog file), cleanup() still tries to remove
the nonexistent container. Solution: check first.

Corner case: fix KeyError in syslog cleanup

---

config_defaults/subtests/docker_cli/build.ini

The docker_cli/build/git_path output checks don't match the behavior
from the Docker file.  Fix this.
The base-image configured for docker_cli/build/http_path doesn't match
the content of it's Dockerfile.  Fix this.

Fix two build sub-subtsts

---

subtests/docker_cli/run_flags/run_flags.py

Kernel 3.10.0-632.el7 (RHEL 7.4 beta) supports the desired
deferred_deletion option. We've been waiting for this.
Update the 3.999 placeholder and remove the FIXME. We now
expect docker-storage-setup to identify this feature and
enable it.
Also, add a debug log so investigators can see the full
docker command line. Possibly useful if test virt has
been wiped.

run_flags: kernel 3.10.0-632 supports deferred_deletion

---

subtests/docker_cli/build/build.py

Fix build logging missing some format parameters.

---

subtests/docker_cli/info/info.py
subtests/docker_cli/info/test_info.py

Up until now, the 'docker info' test has only had
to deal with devicemapper. Now there's overlay2,
and the docker info output for it is significantly
different. Much of the devicemapper validation is
not applicable to overlay2.
Split the storage-handler validation into individual
functions for each driver: currently devicemapper
and overlay2, each of which has different tunables.
As more back ends are added, we can add new functions
to check their settings.
Also: rewrite _build_table() so it handles sub-elements,
and add a unit test.

info subtest: handle overlay2 driver

---

subtests/docker_cli/info/info.py

- add an actual useful diagnostic to an exception
- add exception handler for no 'Storage Driver' subinfo
- cleanup

info subtest: belated review feedback from pr705

---

control

Atomic host doesn't have ``/var/log/audit``, so all selinux stuff goes into
``/var/log/messages``.  In all cases we should be grabbing a copy of both
after every test.

Grab messages in addition to audit.log

---

config_defaults/subtests/docker_cli/run.ini

Extremely simple test, runs the ``yum -y update`` command inside a
container, verifying exit status 0.  Additionally, this test
configuration acts as a placeholder, to be overridden by a more
complex for testing other distros, such as RHEL.
In particular, RHEL maintains patches against upstream docker that
manipulate behavior in subtle ways.  For example, by sharing a
special "secrets" volume mount, to enable subscription-manager
to do it's job inside a RHEL base-image container.
This test enables both verifying the simple case, and the more complex
code paths present where additional docker behavior is involved.

Add test: Verify yum -y update works in container

---

control

When SafeConfigParser is initialized with a defaults dict,
it results in production of a ``[DEFAULTS]`` section when written.
For some reason this prevents properly connecting to bugzilla.
Possibly because the default keys are applied globally, to all sections.
Fix this by not passing a defaults dict, and instead hard-coding the
expected format (including sections) of this file.  This prevents
output of a ``[DEFAULTS]`` section and the BZ search happens normally.

Fix Broken BZ search by DEFAULTS section

---

dockertest/output/dockerversion.py

This is mostly just in case anyone takes this class as a starting place
for something else.  It really should call super() otherwise
mult-inheritance subclasses can easily do very odd/unexpected things.

Add a fixme: Don't leave bad-examples lying around

---

config_defaults/docker_test_images.ini
config_defaults/log_versions.ini
config_defaults/pretests.ini
pretests/log_versions/log_versions.py

For testing/debugging purposes, sometimes additional context from
of other RPM versions is needed.  However, simply listing all
installed RPMss would become burdensome to store and parse.
Instead, feed the ``log_versions`` pre-test a configurable list of
names, and have it store those rpms versions (if installed) into a
separate ``key_rpms`` file.  This file can then be picked up later by
automation to provide additional context when necessary.

Add logging of docker/container-related RPM versions

---

config_defaults/subtests/docker_cli/run.ini

Previously this test's configuration assumed it was running on a CentOS
image.  Testing on CentOS by default was dropped long ago.  Update this
test's configuration to be more generic, but issue warnings if it's not
customized.

Fix run/run_install

---

config_defaults/subtests/docker_cli/pull.ini

When a subtest/sub-subtest overrides one of the test-image component
values, it must set unused components to empty, otherwise they will
inherit possibly-incorrect values from defaults.ini

Fix docker_cli/pull default user value

---

config_defaults/log_versions.ini
pretests/log_versions/log_versions.py

Previously versions of the various docker RPMS was collected in two
places. This is redundant possibly ambiguous, and unnecessary.  The
"active" version of docker is also meaningless since subtests are free
to restart at will.  It would only represent the active version when the
pretest runs.  Better to leave making any declaration of "active"
version up to any subtests where it matters (none currently).

Simplify log_versions

---

subtests/docker_cli/deferred_deletion/deferred_deletion.py
subtests/docker_cli/deferred_deletion/test-deferred-deletion.sh

Per vgoyal: the functionality is still important, let's not
allow it to regress. This reintroduces the test, with a
few minor changes from before:
* Remove the check for devicemapper: docker-storage-setup
only enables deferred_deletion on devicemapper. Even
the broken RHEL 7.2 version.
* Don't just check for the existence of /proc/sys/fs/may_detach_mounts;
read it and confirm that it's enabled.
* Only do the /proc/sys/fs/may_detach_mounts check on RHEL.
This lets the test run on Fedora, which never had the
kernel bug requiring that sysctl switch.

Reenable deferred_deletion test

---

config_defaults/subtests/docker_cli/build.ini
subtests/docker_cli/build/build.py
subtests/docker_cli/build/expose.py

Docker ``1.12+`` regresses WRT this bug in that it adds additional
escape-codes to docker build output.  This is being (correctly)
caught by the ``OutputGood()`` check, however the bug seems
unlikely to ever be fixed.  Unfortunately, removing the check
isn't enough, because many sub-subtests also rely on regular-expression
matching against output.
For example, searching for ``^'Schazam!$'`` where the build output is:
```
Step 4/6 : RUN echo "Schazam!"
---> Running in cc59317feb51
[91m[0mSchazam!
---> 8a359f725df3
Removing intermediate container cc59317feb51
```
Would fail to match due to escape codes at the start of the important
line.  This commit adds a configurable option, defaulting to "off" which
enables checking for escape codes in ``OutputGood()``.  It also removes
the …

Workaround docker-latest build re: BZ 1403326

---

config_defaults/subtests/docker_cli/run_volumes.ini
subtests/docker_cli/run_volumes/run_volumes.py
subtests/docker_cli/run_volumes/test_oci_umount.py

oci-umount is a new (July 2017) docker plugin that unmounts
certain filesystems before a container is started. This test
looks for the presence of /etc/oci-umount.conf and, if it
exists, runs a container with a number of bind mounts and
ensures that no path mentioned in the .conf file is mounted
in the container.
Tested on RHEL 7.4, docker-1.12.6-45.git1680dd8.el7, works
fine.
Tested on RHEL 7.3, docker-1.12.6-32.git88a4867.el7, skips
with Test_NA. Tested by copying /etc/oci-umount.conf from
a RHEL 7.4 box, and test fails with long list of filesystems
that should not be mounted (i.e. it works as expected).
Tested on RHEL 7.4 with containerized docker 1.12.6-8. Test
does not actually pass, but it may be a problem in the
containerized docker build (older oci-umount). Am submitting
for …

new oci-umount test

---

config_defaults/subtests/docker_cli/run_volumes.ini
subtests/docker_cli/run_volumes/run_volumes.py

Intended as a short-lived test, to be removed maybe Sept 2017.
Purpose is to confirm that this regression is fixed on all
distributed builds of docker.
This tests for a corner case in oci-umount that triggers
a SEGV. Test fails (correctly) in docker-1.12.6-47.git0fdc778.el7,
passes in -48.

new test: oci_umount_bz1472121

---

dockertest/config.py
dockertest/containers.py
dockertest/docdeps.py
dockertest/dockercmd.py
dockertest/documentation.py
dockertest/images.py
dockertest/output/dockerinfo.py
dockertest/output/texttable.py
dockertest/output/unseenlines.py
dockertest/output/validate.py
dockertest/subtest.py
dockertest/subtestbase.py
dockertest/textwriter.py
run_pylint.sh
subtests/docker_cli/build/build.py
subtests/docker_cli/events/events.py
subtests/docker_cli/images/images.py
subtests/docker_cli/kill_bad/kill_bad.py
subtests/docker_cli/negativeusage/negativeusage.py
subtests/docker_cli/pull/wrong_registry_addr.py
subtests/docker_cli/run_cgroups/cpushares.py
subtests/docker_cli/run_cgroups/memory.py
subtests/docker_cli/run_volumes/run_volumes.py
subtests/docker_cli/version/version.py
subtests/example/example.py

This is the usual new-Fedora cleanup checkin. It resolves
problems detected by a new version of pylint (1.7.1, up
from 1.6.4 in f25).
The vast majority of the fixes were simple and need little explanation:
C1801:[...]: Do not use `len(SEQUENCE)` as condition value  (26)
R1705:[...]: Unnecessary "else" after "return"              (25)
R0123:[...]: Comparison to literal                          (13)
(number in parentheses is the total count of this warning).
This one needs just a minor note:
W0235:[...]: Useless super delegation in method 'xxxxxx'    (12)
-- mostly fixed by removing superfluous code. In the case
of example.py, I just added useless demo code that
references self.stuff[].
The rest need explaining:
W0221:[...]: X.lmnop: Parameters differ from overridden 'lmnop' method
-- 3 …

HUGE: pylint cleanup for Fedora 26

---

dockertest/images.py

An pedantic-check for a non-float value from a test's configuration
prints a warning that's not very useful in most cases.  Kill it.

Get rid of useless warning message

---

config_defaults/docker_test_images.ini
index.rst

If it's there, then docker feels compelled to try and contact the
localhost registry (which doesn't exist).  Instead, if the
default test image was deleted, we want tests to fail as early as
possible.
Also updated documentation.  This change needs to be paired with
a similar change being made in ADEPT.
[skip-ci]

fix namespace designation WRT fedora_test_image

---

dockertest/subtest.py

With a setup to run tests on Fedora 26 (pre-built image),
given the following in ``config_custom/control.ini``
exclude = docker_test_images/puller
subthings = docker_cli/dockerhelp
and the following in ``config_custom/subtests.ini``
[docker_test_images]
subsubtests = builder
extra_fqins_csv =
build_name = fedora_test_image:latest
build_dockerfile = https://github.com/autotest/autotest-docker/raw/master/fedora_test_image.tar.gz
build_opts_csv = --pull,--force-rm
update_defaults_ini = True
The ``SubSubtestCaller`` caller class will fail with an error trying to
find 'docker_test_images/puller' (referenced by exclude) in
``subsubtests``.  This was originally intended to track down missing,
but expected sub-subtests during configuration processing.
It already (correctly) ignores bugzilla …

Fix looking for excluded sub-subtest configs

---

.papr.yml

Temp. Workaround broken CentOS/EPEL pylint package

---

.papr.yml

This reverts commit a4f40a27acfaf9f9c8adf4e0bf46611cf92f9eec.
[--args=docker_cli/version]

Revert "Temp. Workaround broken CentOS/EPEL pylint package"

---

subtests/docker_cli/run_attach/run_attach.py

coreutils 8.25(?) introduces unexpected behavior changes in
output: many file paths are now in quotes:
- ls: cannot access /foo/bar: No such file or directory
+ ls: cannot access '/foo/bar': No such file or directory
We now accept either form.

Workaround: cope with changes in ls output

---

subtests/docker_cli/run_cgroup_parent/run_cgroup_parent.py

Fedora 26 /proc/1/cgroup includes the line '0::/init.scope',
i.e. the second field is empty. Our code was not expecting
that. Deal with it.
[--args=docker_cli/run_cgroup_parent]

run_cgroup_parent test: don't require a controller

---

config_defaults/subtests/docker_cli/cp.ini
subtests/docker_cli/cp/cp.py

The cp/every_last test invokes a hairy python script (via
command line) in a container. This fails when using a
Fedora 26 image.
First failure: fedora26 image includes /usr/bin/python3
but no plain python.
* Solution: parameterize the name of the python executable,
using new .ini field. CI environment using Fedora images
can replace python with python3
Second failure: test fails with:
TypeError: write() argument must be str, not bytes
* Cause: python3 seems stricter about writing binary data to
stdout; probably a UTF-8 requirement.
* Solution: use stdout.buffer if available (python3 only),
otherwise continue using stdout for output.
[--args=docker_cli/cp]

cp/every_last test: add python3 support

---

subtests/docker_cli/run_flags/run_flags.py

The 'use_deferred_removal' flag is only required (and only
appropriate) when using devicemapper. The world is moving
toward overlay2. Skip this test when not on devicemapper.
Also, significant cleanup: use simple string check instead
of cumbersome list iteration; use failif_not_in(); remove
no-longer-used helper code. (Background: this subtest
originally also had a check for deferred deletion so it
made sense to refactor commonalities.)
[--args=docker_cli/run_flags]

run_flags: only run when storage == devicemapper

---

dockertest/subtestbase.py

WARNING: Test results may be externally dependent! (See debug log for details
This message only points to a possible source of problems, it's
excessive logging at the WARNING level is basically just noise.
Since there's already a more specific warning at the DEBUG level, this
one can simply be killed outright.

Remove annoying warning

---

dockertest/images.py
dockertest/images_unittests.py

Every so often the build subtest fails and leaves behind
an untagged intermediate image. This causes a cascade of
garbage_check failures:
Found leftover images from prior test: [DockerImage(....)]
Root cause is that garbage_check _tries_ to remove these
images, but the underlying code was calling remove_by_fullname()
and fullname is undefined because TAG is <none>.
Solution: remove by image ID (hash), not name. This is reliable.

images:remove_image_by_image_obj() - remove by ID, not name

---

dockertest/images.py
dockertest/images_unittests.py

The previous PR was buggy: docker can't remove an image by ID
if the image is tagged more than once, e.g.
docker.io/fedora     latest     b0b140824a48
docker.io/fedora     7          b0b140824a48
The error is:
conflict: unable to delete b0b140824a48 (must be forced) - image is referenced in multiple repositories
Solution: only remove by ID if the image has no tag. Otherwise
(default case) remove by fullname. This may not always work;
we may need to fall back to:
docker rmi $(docker images -f dangling=true -q)
Unfortunately, I can't manage to reliably reproduce the
case where an image has a name but no tag; this means I
can't actually test this code.

Followup: removing images

---

config_defaults/intratests.ini
dockertest/docker_daemon.py
dockertest/docker_daemon_unittests.py
intratests/garbage_check/garbage_check.py
subtests/docker_cli/liverestore/liverestore.py

This functionality (editing /etc/sysconfig/docker* and
restarting docker daemon) was never used and is unlikely
ever to be used. Let's remove it.
This reverts commit aa6b7dd55722c697e1cc133211ed1a05b4097ce2.

Revert "Functionality for restarting docker daemon (#635)"

---

dockertest/docker_daemon.py
dockertest/subtest.py
subtests/docker_cli/run_dns/run_dns.py
subtests/docker_cli/run_volumes_selinux/run_volumes_selinux.py
subtests/docker_cli/selinux_labels/test.sh
subtests/docker_cli/top/runsleep.py

Fixes the following test failures when running with user namespaces:
- run_dns : Privileged mode is incompatible with user namespaces
Solution: run docker client with '--userns=host' option
when running with userns
- run_volumes_selinux : permission denied
cause : subtest creates a tmpdir
solution : chown the tmpdir when running with userns
- selinux_labels      : Privileged mode is incompatible with user namespaces
solution : run docker client with '--userns=host' option
- top                 : incorrect userid (not 'root')
solution : read /etc/subuid when running with userns
- anything with -v    : permission denied
cause : tmp dirs are 700 owned by root
solution : chown when running with userns

workarounds for user namespace testing

---

subtests/docker_cli/dockerhelp/dockerhelp.py

The dockerhelp subtest that was supposed to be checking
invalid commands ('docker --help --quiet', 'docker foobar')
was not actually doing anything useful. Remove nonuseful
code, replacing it with a simple check for output on
stderr: we don't check content, just check that something
was emitted on stderr.
Also, for proper help commands that should succeed,
make sure exit status is 0.

dockerhelp: fix nonfunctional test
